### ISSUE TITLE
Question on struct Struct03003080 (gLCDControlBuffer)

### ISSUE THREAD

**Issue by MokhaLeee** [FireEmblemUniverse/fireemblem8u#144]
take such code:
`
void test(){	
	/* 04 */
	gLCDControlBuffer.dispstat.vblankFlag = 1;
}
`

then we will get such asm code:

movs	r1, #1
ldr		r2, gLCDControlBuffer
ldrb		r3, [r2, #2]
orrs		r3, r1
strb		r3, [r2, #2]
bx		lr

According to struct definition, gLCDControlBuffer.dispstat.vblankFlag should be located at struct + 0x4, rather than 0x2. So I feel there are some problems on definition of struct  Struct03003080 in types.h.

**Comment by laqieer** [comment]
I checked generated assembly. It doesn't have any problem.
https://github.com/FireEmblemUniverse/fireemblem8u/blob/c90d89062ff25c7991efa5385f3959a2d339159c/src/hardware.c#L50
```
        .type    FlushLCDControl,function
        .thumb_func
FlushLCDControl:
.LFB3:
.LM16:

.LM17:

        mov     r1, #0x80
        lsl     r1, r1, #0x13
        ldr     r2, .L19
        ldrh    r0, [r2]
        strh    r0, [r1]
.LM18:

        add     r1, r1, #0x4
        ldrh    r0, [r2, #0x4] <------------
        strh    r0, [r1]
```

**Comment by laqieer** [comment]
It is obvious that you are using this file in projects other than decomp project and you didn't configure your compiler to deal with structure packing correctly. The problem doesn't belong to decomp project and you can read these docs to find out how to fix it in your project:
- https://gcc.gnu.org/onlinedocs/gcc/Structure-Layout-Pragmas.html#Structure-Layout-Pragmas
- https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#Common-Type-Attributes

**Comment by MokhaLeee** [comment]
I'm not sure what exactly the problem is, but now I have to insert some pads...
![image](https://user-images.githubusercontent.com/89029102/155275002-c1a7e258-835d-4c05-aa65-7ed080d22244.png)
maybe problem lies in my compiling methoud?
```
INC_DIRS := $(realpath include) $(CLIB_DIR)/include
INCFLAGS     := $(foreach dir, $(INC_DIRS), -I "$(dir)")
ARCH    := -mcpu=arm7tdmi -mthumb -mthumb-interwork
CFLAGS  := $(ARCH) $(INCFLAGS) -Wall -O2 -mtune=arm7tdmi -ffreestanding -mlong-calls
CDEPFLAGS = -MMD -MT "$*.o" -MT "$*.asm" -MF "$(CACHE_DIR)/$(notdir $*).d" -MP
%.o: %.c
	@$(CC) $(CFLAGS) $(CDEPFLAGS) -g -c $< -o $@ $(ERROR_FILTER)
```

**Comment by MokhaLeee** [comment]
thanks a lot

**Comment by MokhaLeee** [comment]
![image](https://user-images.githubusercontent.com/89029102/155282632-3f58e129-48ad-4f0a-ac32-e093f472f283.png)
Made it, just add some align commands

**Comment by laqieer** [comment]
I think this issue can be closed if you don't have other questions.
