### ISSUE TITLE
don't understand

### ISSUE THREAD

**Issue by Kira-YamatoTZC** [FireEmblemUniverse/fireemblem8u#224]
why have some .s file in the .c file,didn't translation .s file to .c file?Thank you for your help.

**Comment by ProjectRevoTPP** [comment]
You're going to have to be a bit more specific.

**Comment by Kira-YamatoTZC** [comment]
#include "global.h"

#include "hardware.h"
#include "ctc.h"
#include "fontgrp.h"
#include "bmmap.h"


struct SubtitleHelpProc {
    /* 00 */ PROC_HEADER;

    /* 2C */ const char* string;
    /* 30 */ struct Font font;
    /* 48 */ struct TextHandle text[2];
    /* 58 */ s16 textOffset;
    /* 5A */ s16 textShowCnt;
    /* 5C */ s16 textNum;
    /* 5E */ s16 textCount;
};

extern u8 gUnknown_0859EF20[]; // pal

// bm.s
void sub_8015EDC(int);

**Comment by Kira-YamatoTZC** [comment]
for example,bb.c file have a function which void sub_8015EDC(int),but this function is in bm.s,why can't translation bm.s to bm.c file?

**Comment by MokhaLeee** [comment]
You can consider the functions in asm folder is just the un-decomped c-functions. It is recommended to refer to this doc:
https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/CONTRIBUTING.md

**Comment by laqieer** [comment]
That function is not supposed to be translated in `bm.c`.
https://github.com/FireEmblemUniverse/fireemblem8u/blob/7a08cc86d4fb738412f721e241d3fb034e5634a8/src/bb.c#L24
This line is a function declaration instead of implementation. It is only for function `SubtitleHelp_OnEnd` to call it.
It is recommended to link to the source code instead of copy and paste it directly here for its context, or place it in a code block at least for the syntax highlight.

**Comment by Kira-YamatoTZC** [comment]
i understand,it don't need to translation,I love this game and I play it many times,thanks your translation.

**Comment by laqieer** [comment]
It does need translation when we decompile `bm.s` to `bm.c` in the future. However, it is not done yet due to lack of hands. It would be appreciated if you help to translate it. It is suggested to read [this doc](https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/CONTRIBUTING.md) to learn how to start to contribute to the project if you like it. Thanks!

**Comment by Kira-YamatoTZC** [comment]
ok,i will try it.but I find it's too less to lean assembly by the doc you give me,if there have more page I can study.And I also look GBA code and study what disambly is.

**Comment by MokhaLeee** [comment]
I think these two tutorials is also important

https://feuniverse.us/t/gba-hacking-in-c/4876

https://feuniverse.us/t/guide-doc-asm-hacking-in-c-with-ea/3351/3

**Comment by laqieer** [comment]
That doc is a guide on how to contribute to this project, assuming that you already know basic knowledges including assembly and C, which are generic embeded programming skills and you can find tutorials on the Internet without much effort. It seems that you already know C but doesn't know assembly yet, so I recommend you to give [this](https://feuniverse.us/t/gbafe-assembly-for-dummies-by-dummies/3563) a read first to learn assembly and read [this](https://feuniverse.us/t/doc-asm-conventions/3350) to learn how a C compiler will interprets C source code to assembly. Then learn how to use a decompiler like [IDA Pro](https://hex-rays.com/IDA-pro/) or [Ghidra](https://ghidra-sre.org/)(open source alternative) to improve your efficiency. A lot to learn, but I still encourage you with this:
![image](https://user-images.githubusercontent.com/8841957/197664768-09370dbf-2c57-439f-a4d4-e176666279f3.png)

**Comment by Kira-YamatoTZC** [comment]
what's function about the scripts?

**Comment by laqieer** [comment]
It is to extract assets from game for decomp, which you needn't focus on now.

**Comment by Kira-YamatoTZC** [comment]
Can I use visual studio to build this program?And i need you give me all the .s file that has been translationed.I can study how to Translate the function to C.Thank you.

**Comment by MokhaLeee** [comment]
It will generate .s files from .c after compiling

**Comment by Kira-YamatoTZC** [comment]
Can you speak Chinese?I saw you speak chinese in net




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FireEmblemUniverse/fireemblem8u"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 上午8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FireEmblemUniverse/fireemblem8u] don't understand (Issue #224)





 
I think these two tutorials is also important
 
https://feuniverse.us/t/gba-hacking-in-c/4876
 
https://feuniverse.us/t/guide-doc-asm-hacking-in-c-with-ea/3351/3

**Comment by Kira-YamatoTZC** [comment]
i am sorry to say that,but i can't build this program and i need all the .s file that has been translationed.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mokha ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 中午1:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FireEmblemUniverse/fireemblem8u] don&#39;t understand (Issue #224)





 
It will generate .s files from .c after compiling

**Comment by ProjectRevoTPP** [comment]
Please stop commenting in a closed issue. Get someone that can speak English. If we can't understand what your issue is we can't help you.

**Comment by Kira-YamatoTZC** [comment]
ok, I know English.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月28日(星期五) 凌晨0:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FireEmblemUniverse/fireemblem8u] don&#39;t understand (Issue #224)





 
Please stop commenting in a closed issue. Get someone that can speak English. If we can't understand what your issue is we can't help you.
