### ISSUE TITLE
textencode does not generate matching text arrays

### ISSUE THREAD

**Issue by jiangzhengwenjz** [FireEmblemUniverse/fireemblem8u#253]
On my machine the tool is compiled with `12.2.1 20221121 (Red Hat 12.2.1-4) (GCC)`. With the default optimization level `-O2` (for textencode), the generated text arrays in `src/msg_data.c` are not matching. 

I changed it to `-O0` and it produced the matching ROM.

**Comment by CT075** [comment]
That's really weird; I can't see anything that would be messed up with `-O2`. I can't test the full build, but on my machine from a fresh clone, I'm also not seeing any difference in the outputs of `textencode` with optimizations on or off (or at least, `diff` is coming up clean). My `gcc --version` also gives the same output.

Can you post your `src/msg_data.c`?

**Comment by jiangzhengwenjz** [comment]
Okay I found the real issue. I pulled from upstream and the tool was not rebuilt. Sorry for your time and thank you for your help.
