### ISSUE TITLE
DWARF error: mangled line number section

### ISSUE THREAD

**Issue by laqieer** [FireEmblemUniverse/fireemblem8u#313]
There is still one line of this error left which is not fixed by https://github.com/pret/agbcc/pull/51:
```
/opt/devkitpro/devkitARM/bin/arm-none-eabi-nm: DWARF error: mangled line number section
```

Reproduced on both local & runner:
https://github.com/FireEmblemUniverse/fireemblem8u/actions/runs/4620090766/jobs/8169711954#step:10:5

Further investigation is needed.

**Comment by StanHash** [comment]
https://github.com/FireEmblemUniverse/fireemblem8u/blob/258c1d437e20cf5615805c2c998a10f0a7788ee6/Makefile#L87

this overrides -ffix-debug-line
