### ISSUE TITLE
4bpp.lz not match

### ISSUE THREAD

**Issue by MokhaLeee** [FireEmblemUniverse/fireemblem8u#472]
GameIntro anim world-map gfx as located as below:

img: 0xAB21D8
tsa: 0xAB5D90
pal: 0xAB630C

I dumped this gfx via FEBuilder, try to replace the at `img_08AB21D8` in file **data/data_AA7760.s**

```asm
	.global img_08AB21D8
img_08AB21D8:  @ 0x08AB21D8
	.incbin "graphics/game_intro/world_map.4bpp.lz"
	#.incbin "baserom.gba", 0xAB21D8, 0x3BB8
```

nonmatching. why?

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fireemblem8u/blob/game-intro2/data/data_AA7760.s#L132

**Comment by RevoSucks** [comment]
Did you check to see if extra data is appended to the final bin? In other projects, such as pokeemerald, some special gfx need extra .mk rules to specify num_tiles if they are a specific size.

**Comment by laqieer** [comment]
Could you please attach the graphic?
